# What does one need to do to use a module?
modules are built into python language.  To use them you must import it them into whatever you are trying to code.  

# Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.

# What is a benefit of using Exception handling?
To write code so it doesn't blow up on you when you're in the middle of finishing a project.  Keeping program from crashing. 

# NumPy arrays are like what Python data type?
They are similar to Lists!

# What is one of the main benefits of using NumPy arrays.
Smaller in size than lists and they take up less space.  They are better at facilitating mathematical operations more efficiently.

# What is one of the main requirements about the 'dtype' of NumPy arrays?
Must be the same data type.  

# Of the 10 uses of NumPy, name 2.
1) copying/viewing arrays 2) Reshaping

# Name one of the other libraries we'll use with NumPy? Pandas 

# What is the shape of NumPy arrays?
 Depends on number of elements/demensions to determine the shape.  

# What is a Tensor?
An array with three or more demensions.  

# Name a reason why it's better using  NumPy for Data Analysis than using a Python List?
Lists are much more bulky and slow to process.  Numpy consolidates data better and processes much quicker.

# When creating an "empty" array, where do the elements come from?
 It'll first be random and depends on the state of the memory.  

In [2]:
#Use the DateTime module to get Current Date and Time, and save it to a variable. 
import datetime as dt
timeage = dt.datetime.now()
print("Current date  and Time...", timeage) 

Current date  and Time... 2023-02-19 15:00:47.631507


In [6]:
#Then extract just the Full month name form that variable.
month = dt.datetime.now()
("Month ...", timeage.strftime("%B")) 


('Month ...', 'February')

In [19]:
#Write a simple function that takes 2 parameters -- a first name and a day name.
def nd(name,day = "tuesday!"):
    print("Sup,", name,"! It's taco", day, "!")
    
nd("Todd", "Tuesday!")




Sup, Todd ! It's taco Tuesday! !


In [1]:
#Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
ARay = np.arange(12).reshape(2,3,2)
print(ARay)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [2]:
#Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
import numpy as np
ARay1 = np.linspace(0,20, num = 6)
print(ARay1)

[ 0.  4.  8. 12. 16. 20.]


In [5]:
#Make a Deep Copy of the above array you created.
import copy
ARay2 = copy.deepcopy(ARay1)
print(ARay2)

[ 0.  4.  8. 12. 16. 20.]


In [ ]:
#What are 2 reasons we use NumPy arrays over Python Lists

#1 they are way faster compared to lists.

#2 they take up less memory space and won't crash VS code because of how compact arrays make data.