#What does Pandas stand for?
* Derived from "Panel Data".  It stands for "Python Data Analysis Library".

#What are the 2 collections used in Pandas?
* Series: 1-dimension 
 DataFrame: 2-dimensional

#Name 4 things Pandas can do for us
*Load, Data cleansing, Data Inspection, Data visualization 

#To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
* values

#What is a CSV
* Comas seperated values = CSV.  A delimited text file that uses commas to separate values 

#When cleaning data what values do we not like in our data?
* Null values

In [9]:
#Concatenate these 3 arrays into a new array named 'newArray'...

([[25, 16]])
([[11, 2], [13, 4]])
([[7, 81], [5, 6], [11, 12]])
import numpy as np 

A1 =np.array([[25, 16]])
A2 =np.array([[11, 2], [13, 4]])
A3 =np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate ((A1, A2, A3))
print("\nnewArray is:\n", newArray)



newArray is:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [11]:
#Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nsortedArray is:\n", sortedArray)


sortedArray is:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [15]:
#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = np.reshape(sortedArray,(2, 2, 3))
print("\nreshapedArray is:\n", reshapedArray)


reshapedArray is:
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]


In [16]:
#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

x,o = reshapedArray 
x0, x1 = x
o0,o1 = o
print(x0,x1,o0,o1)

[16 25  2] [11  4 13] [ 7 81  5] [ 6 11 12]


In [18]:
#Combined and sort the following arrays into one called 'comboArray' ...

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print("\ncomboArray is:\n", comboArray)


comboArray is:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [25]:
#Take 'comboArray' and perform the following slicing activities

#print sec1 - the 2nd element

print(comboArray[1])

#print sec2 - all elements from the 3rd element to the last

print(comboArray[2:])

#print sec3 - all elements from the 4th to the 14th elements

print(comboArray[3:15])

#print sec4 - the last 6 elements

print(comboArray[-6:])

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.

print(comboArray[:-10]) 

#print sec6 - from #20 every even element to the end

print(comboArray[16::2])

#print sec7 - from the last element moving forward, every 5th element.

print(comboArray[-1::-5])

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [31]:
#Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --

([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

([[17.0, 70.0, 10.7]])


A1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
       [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

B2 = np.array([[17.0, 70.0, 10.7]])

#the addition (+)

print(A1 + B2)

#division (/)

print(A1 / B2)

#multiplication (*)

print(A1 * B2)

#Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.

print(np.subtract(A1, B2))

#Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.

print(A1[A1 % 3 == 0])

[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]
[ 0.  0. 30. 24. 15.]


In [33]:
#Using Series, create a DataFrame that looks like this:  #see example in dap_curriculum folder.

import pandas as pd

I = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name= "Ingredients")
Q = pd.Series([4, 1, 2, 1], name= "Quantity")
U = pd.Series(['cups', 'cup', 'large', 'can'], name= "unit")

#Name: Dinner, dtype: object

df = pd.concat([I, Q, U], axis=1)
df.name = "Dinner"
print(df)


  Ingredients  Quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [35]:
#Take this data and create a DataFrame named studentData #see example in dap_curriculum folder #11

studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(studentData)
studentData.name = "studentData"
print("\nDataframe names: studentData:\n", studentData)


Dataframe names: studentData:
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [36]:
#Add a new column to the DataFrame with deserts:["ice cream", "Cashew Fudge","waffels", "Carrot Halwa"]

studentData.insert(7, "Deserts", ["ice cream", "cashew Fudge", "waffles", "Carrot Halwa"])
print("\nInsert dedsert column:\n", studentData)


Insert dedsert column:
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  cashew Fudge  
2       waffles  
3  Carrot Halwa  


In [40]:
#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ["Name", "address"], inplace=True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffles  
0     ice cream  
1  cashew Fudge  


In [41]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
studentData.to_csv("cows_and_goats.csv")

In [ ]:
#(A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, 
#and save a copy with a different name.

#wait.... what????  